layout: page
title: Statistical and Mathematical Methods for Data Science (FALL_2023)
#permalink: /URL-PATH
description: Weekly Course Outline
email: shahid.ashraf@fast.nu.edu.pk
theme: jekyll-theme-minimal
markdown: GFM
